// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "ui/base/l10n/chromium_language_matcher.h"

#include <iterator>
#include <vector>

#include <array>
#include "base/i18n/language_tag.h"
#include "base/i18n/language_tag_matcher.h"
#include "base/no_destructor.h"
#include "ui/base/buildflags.h"

namespace ui_l10n {
namespace {

using ::base::i18n::GetKnownLanguageTag;
using ::base::i18n::LanguageTag;
using ::base::i18n::LanguageTagMatcher;

constexpr auto kPlatformLocales = std::to_array<LanguageTag>({
#define PLATFORM_LOCALE(locale) GetKnownLanguageTag(#locale),
// The below is generated by tools/l10n/generate_locales_list.py, which is
// run in the //ui/base:locales_list_gen build rule.
#include "ui/base/l10n/l10n_util_locales_list.inc"
#undef PLATFORM_LOCALE
});

}  // namespace

base::span<const LanguageTag> GetPlatformLanguageTags() {
  return base::span(kPlatformLocales);
}

COMPONENT_EXPORT(UI_BASE)
const LanguageTagMatcher& GetPlatformLanguageMatcher() {
  static base::NoDestructor<LanguageTagMatcher> matcher(
      LanguageTagMatcher::Create(kPlatformLocales));
  return *matcher;
}

}  // namespace ui_l10n
