# Copyright 2022 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/features.gni")
import("//build/config/linux/gtk/gtk.gni")

assert(is_linux)

component("linux_ui") {
  defines = [ "IS_LINUX_UI_IMPL" ]
  public = [
    "cursor_theme_manager_observer.h",
    "device_scale_factor_observer.h",
    "linux_ui.h",
    "linux_ui_delegate.h",
    "linux_ui_delegate_stub.h",
    "linux_ui_getter.h",
    "nav_button_provider.h",
    "primary_paste_pref_observer.h",
    "status_icon_linux.h",
    "window_button_order_observer.h",
    "window_frame_provider.h",
  ]
  sources = [
    "linux_ui.cc",
    "linux_ui_delegate.cc",
    "linux_ui_delegate_stub.cc",
    "linux_ui_getter.cc",
    "status_icon_linux.cc",
  ]
  deps = [
    "//base",
    "//ui/base:types",
    "//ui/display/types",
    "//ui/gfx/geometry",
  ]
}


source_set("test_support") {
  testonly = true

  public = [ "fake_linux_ui.h" ]
  sources = [ "fake_linux_ui.cc" ]

  public_deps = [ ":linux_ui" ]
  deps = [
    "//base",
    "//skia",
    "//ui/base/ime/linux",
    "//ui/gfx",
    "//ui/native_theme",
  ]
}
