# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#requires -Version 7.0

# Phase 0 input lock.
#
# docs/minimal-checkout.md section 6 lists what has to be recorded and verified
# before anything is fetched: Chromium commit, depot_tools commit, DEPS
# SHA-256, .gclient custom_vars/custom_deps, target_os/target_cpu, the GN args
# and their SHA-256, and the hook names, order and actions. This module builds
# that document from read-only inspection of a reference checkout and the pinned
# depot_tools, and re-verifies it against a materialised checkout in Phase 1.
#
# Nothing here touches the network or writes to the reference checkout.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Export-ShotGitBlob {
    <#
    .SYNOPSIS
        Writes one blob from a pinned commit to a file, byte for byte.
    .DESCRIPTION
        The redirection has to be byte-level: DEPS is hashed, and letting
        PowerShell re-encode the stream would change the SHA-256 and silently
        break every comparison against the doc.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$RepositoryPath,
        [Parameter(Mandatory)][string]$Commit,
        [Parameter(Mandatory)][string]$BlobPath,
        [Parameter(Mandatory)][string]$OutFile
    )

    $psi = [System.Diagnostics.ProcessStartInfo]::new()
    $psi.FileName = 'git'
    foreach ($a in @('-C', $RepositoryPath, 'cat-file', 'blob', "${Commit}:${BlobPath}")) {
        [void]$psi.ArgumentList.Add($a)
    }
    $psi.RedirectStandardOutput = $true
    $psi.RedirectStandardError = $true
    $psi.UseShellExecute = $false

    $process = [System.Diagnostics.Process]::Start($psi)
    $stream = [System.IO.File]::Create($OutFile)
    try {
        $process.StandardOutput.BaseStream.CopyTo($stream)
    } finally {
        $stream.Dispose()
    }
    $stderr = $process.StandardError.ReadToEnd()
    $process.WaitForExit()
    if ($process.ExitCode -ne 0) {
        throw "git cat-file blob ${Commit}:${BlobPath} failed in ${RepositoryPath}: $stderr"
    }
    $OutFile
}

function Get-ShotGitBlobText {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$RepositoryPath,
        [Parameter(Mandatory)][string]$Commit,
        [Parameter(Mandatory)][string]$BlobPath,
        [switch]$AllowMissing
    )

    $temp = [System.IO.Path]::GetTempFileName()
    try {
        Export-ShotGitBlob -RepositoryPath $RepositoryPath -Commit $Commit -BlobPath $BlobPath -OutFile $temp | Out-Null
        $bytes = [System.IO.File]::ReadAllBytes($temp)
        [pscustomobject]@{
            Path   = $BlobPath
            Bytes  = $bytes.Length
            Sha256 = (Get-FileHash -LiteralPath $temp -Algorithm SHA256).Hash.ToLowerInvariant()
            Text   = [System.Text.Encoding]::UTF8.GetString($bytes)
        }
    } catch {
        if ($AllowMissing) { return $null }
        throw
    } finally {
        Remove-Item -LiteralPath $temp -Force -ErrorAction SilentlyContinue
    }
}

function Read-ShotCustomDepsFile {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) { throw "custom_deps batch file not found: $Path" }
    $raw = [System.IO.File]::ReadAllBytes($Path)
    $lines = [System.Text.Encoding]::UTF8.GetString($raw) -split "`r?`n"
    $paths = foreach ($line in $lines) {
        $stripped = ($line -split '#', 2)[0].Trim()
        if ($stripped) { $stripped }
    }
    $paths = @($paths)
    $duplicates = @($paths | Group-Object | Where-Object Count -gt 1 | ForEach-Object Name)
    if ($duplicates.Count -gt 0) {
        throw "Duplicate entries in ${Path}: $($duplicates -join ', ')"
    }
    foreach ($p in $paths) {
        # Every DEPS key is rooted at the solution name. A path missing the
        # prefix silently matches nothing and would look like a saving that
        # never happened.
        if ($p -notlike 'src/*') { throw "custom_deps entry must start with 'src/': '$p' in $Path" }
    }
    [pscustomobject]@{
        Path   = $Path
        Sha256 = (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
        Paths  = $paths
        Count  = $paths.Count
    }
}

function New-ShotGclientContent {
    <#
    .SYNOPSIS
        Renders the .gclient for the isolated target.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$SolutionName,
        [Parameter(Mandatory)][string]$Url,
        [Parameter(Mandatory)][hashtable]$CustomVars,
        [Parameter(Mandatory)][string[]]$CustomDeps,
        [Parameter(Mandatory)][string]$TargetOs
    )

    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('# Generated by bootstrap/bootstrap.ps1. Do not hand-edit.')
    [void]$sb.AppendLine('#')
    [void]$sb.AppendLine('# The solution is named "src" and sits one level below this file because')
    [void]$sb.AppendLine('# every DEPS key is written as "src/...". managed = False keeps gclient from')
    [void]$sb.AppendLine('# moving the pinned commit underneath us.')
    [void]$sb.AppendLine('solutions = [')
    [void]$sb.AppendLine('  {')
    [void]$sb.AppendLine("    `"name`"      : '$SolutionName',")
    [void]$sb.AppendLine("    `"url`"       : '$Url',")
    [void]$sb.AppendLine("    `"deps_file`" : 'DEPS',")
    [void]$sb.AppendLine('    "managed"   : False,')
    [void]$sb.AppendLine('    "custom_deps" : {')
    foreach ($dep in $CustomDeps) {
        [void]$sb.AppendLine("      '$dep': None,")
    }
    [void]$sb.AppendLine('    },')
    [void]$sb.AppendLine('    "custom_vars": {')
    foreach ($key in ($CustomVars.Keys | Sort-Object)) {
        $value = $CustomVars[$key]
        $rendered = if ($value -is [bool]) { if ($value) { 'True' } else { 'False' } } else { "'$value'" }
        [void]$sb.AppendLine("      '$key': $rendered,")
    }
    [void]$sb.AppendLine('    },')
    [void]$sb.AppendLine('  },')
    [void]$sb.AppendLine(']')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("target_os = ['$TargetOs']")
    [void]$sb.AppendLine('target_os_only = True')
    $sb.ToString()
}

function New-ShotArgsGnContent {
    <#
    .SYNOPSIS
        Renders out/<dir>/args.gn.
    .DESCRIPTION
        target_os and target_cpu are written explicitly even though they match
        the host default: they are locked inputs, and a lock that relies on
        host detection is not a lock.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$ArgsTemplate,
        [Parameter(Mandatory)][string]$TargetOs,
        [Parameter(Mandatory)][string]$TargetCpu
    )

    @(
        '# Generated by bootstrap/bootstrap.ps1. Do not hand-edit.'
        "import(`"$ArgsTemplate`")"
        "target_os = `"$TargetOs`""
        "target_cpu = `"$TargetCpu`""
        ''
    ) -join "`n"
}

function Invoke-ShotDepsEvaluation {
    <#
    .SYNOPSIS
        Runs lib/deps_lock.py against a DEPS blob with the pinned depot_tools.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Python,
        [Parameter(Mandatory)][string]$ScriptPath,
        [Parameter(Mandatory)][string]$DepsFile,
        [Parameter(Mandatory)][string]$DepotTools,
        [Parameter(Mandatory)][string]$CustomDepsFile,
        [Parameter(Mandatory)][hashtable]$CustomVars,
        [switch]$IncludeDeps,
        [switch]$BaselineMatrix
    )

    $arguments = @(
        $ScriptPath
        '--deps-file', $DepsFile
        '--depot-tools', $DepotTools
        '--custom-deps-file', $CustomDepsFile
        '--custom-vars', (ConvertTo-Json $CustomVars -Compress)
    )
    if ($IncludeDeps) { $arguments += '--include-deps' }
    if ($BaselineMatrix) { $arguments += '--baseline-matrix' }

    $output = & $Python @arguments 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "deps_lock.py failed ($LASTEXITCODE):`n$($output -join "`n")"
    }
    ($output -join "`n") | ConvertFrom-Json
}

# Numbers that docs/minimal-checkout.md section 7.3 pins for this HEAD. If the
# evaluator disagrees, either DEPS is not the pinned one, depot_tools drifted,
# or the candidate batch was edited. All three invalidate the lock, so this is
# an error rather than a note.
$script:DocBaseline = @{
    default      = @{ remaining = 187; git = 139; cipd = 33; gcs = 15 }
    small        = @{ remaining = 180; git = 132; cipd = 33; gcs = 15 }
    'small+null' = @{ remaining = 133; git = 115; cipd = 11; gcs = 7 }
}

function Assert-ShotDocBaseline {
    [CmdletBinding()]
    param([Parameter(Mandatory)]$Matrix)

    $problems = [System.Collections.ArrayList]::new()
    foreach ($label in $script:DocBaseline.Keys) {
        $expected = $script:DocBaseline[$label]
        $actual = $Matrix.$label
        if (-not $actual) { [void]$problems.Add("missing row '$label'"); continue }
        foreach ($field in $expected.Keys) {
            if ($actual.$field -ne $expected[$field]) {
                [void]$problems.Add("$label.$field expected $($expected[$field]) got $($actual.$field)")
            }
        }
    }
    if ($problems.Count -gt 0) {
        throw ("DEPS evaluation does not match docs/minimal-checkout.md section 7.3:`n  " + ($problems -join "`n  "))
    }
    $true
}

function New-ShotInputLock {
    <#
    .SYNOPSIS
        Builds the Phase 0 lock document from read-only inputs.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]$Context,
        [Parameter(Mandatory)][hashtable]$Settings
    )

    $reference = $Settings.ReferenceCheckout
    if (-not $reference -or -not (Test-Path -LiteralPath (Join-Path $reference '.git'))) {
        throw "A reference checkout is required to build the input lock; '$reference' is not a git repository."
    }

    # The pinned commit must actually be reachable in the reference checkout,
    # otherwise the DEPS and hook facts below would describe a different tree.
    & git -C $reference cat-file -e "$($Settings.ChromiumCommit)^{commit}" 2>$null
    if ($LASTEXITCODE -ne 0) {
        throw "Pinned Chromium commit $($Settings.ChromiumCommit) is not present in the reference checkout $reference."
    }

    $forkRef = $null
    $forkCommits = @()
    if (-not $Settings.SkipForkOverlay) {
        $forkRef = Get-ShotFirstLine (& git -C $reference rev-parse "$($Settings.ForkRef)^{commit}" 2>$null)
        if ($LASTEXITCODE -ne 0 -or -not $forkRef) {
            throw "Fork overlay ref '$($Settings.ForkRef)' does not resolve in $reference."
        }
        & git -C $reference merge-base --is-ancestor $Settings.ChromiumCommit $forkRef 2>$null
        if ($LASTEXITCODE -ne 0) {
            throw "Fork ref $forkRef does not descend from the pinned commit $($Settings.ChromiumCommit); the overlay would not be a pure addition on top of the pin."
        }
        $log = & git -C $reference log --reverse --format='%H%x1f%s' "$($Settings.ChromiumCommit)..$forkRef" 2>$null
        $forkCommits = @(foreach ($line in @($log)) {
            if (-not $line) { continue }
            $parts = ([string]$line) -split "`u{001f}", 2
            $files = @(& git -C $reference diff-tree --no-commit-id --name-only -r $parts[0] 2>$null | ForEach-Object { [string]$_ })
            [pscustomobject]@{ commit = $parts[0]; subject = $parts[1]; files = $files }
        })
    }

    $deps = Get-ShotGitBlobText -RepositoryPath $reference -Commit $Settings.ChromiumCommit -BlobPath 'DEPS'

    # The GN args template lives in the fork, not upstream. Read it from the
    # overlay tip so the lock records what gn gen will actually import.
    $argsSourceCommit = if ($forkRef) { $forkRef } else { $Settings.ChromiumCommit }
    $gnArgsTemplateRepoPath = ($Settings.GnArgsTemplate -replace '^//', '')
    $gnArgsBlob = Get-ShotGitBlobText -RepositoryPath $reference -Commit $argsSourceCommit `
        -BlobPath $gnArgsTemplateRepoPath -AllowMissing
    if (-not $gnArgsBlob) {
        throw "GN args template '$($Settings.GnArgsTemplate)' does not exist at $argsSourceCommit in $reference. Phase 1 would generate an args.gn that imports a missing file."
    }

    $customDeps = Read-ShotCustomDepsFile -Path $Settings.CustomDepsFile
    $customVars = @{ checkout_configuration = $Settings.CheckoutConfiguration }

    # deps_lock.py needs the DEPS blob on disk; keep it inside the run state so
    # the evaluated artefact and its inputs stay together.
    $depsCopy = Join-Path $Context.StateRoot 'DEPS.pinned'
    if ($Context.DryRun) {
        $depsCopy = [System.IO.Path]::GetTempFileName()
        [System.IO.File]::WriteAllText($depsCopy, $deps.Text, [System.Text.UTF8Encoding]::new($false))
    } else {
        Export-ShotGitBlob -RepositoryPath $reference -Commit $Settings.ChromiumCommit -BlobPath 'DEPS' -OutFile $depsCopy | Out-Null
    }

    $evaluation = Invoke-ShotDepsEvaluation -Python $Settings.Python -ScriptPath $Settings.DepsLockScript `
        -DepsFile $depsCopy -DepotTools $Settings.DepotTools -CustomDepsFile $Settings.CustomDepsFile `
        -CustomVars $customVars -BaselineMatrix -IncludeDeps:$Settings.IncludeDeps

    if ($evaluation.depsSha256 -ne $deps.Sha256) {
        throw "DEPS hash mismatch between the git blob ($($deps.Sha256)) and the evaluated copy ($($evaluation.depsSha256))."
    }
    Assert-ShotDocBaseline -Matrix $evaluation.baselineMatrix | Out-Null

    $gclientContent = New-ShotGclientContent -SolutionName $Settings.SolutionName -Url $Settings.ChromiumRemote `
        -CustomVars $customVars -CustomDeps $customDeps.Paths -TargetOs $Settings.TargetOs
    $argsGnContent = New-ShotArgsGnContent -ArgsTemplate $Settings.GnArgsTemplate `
        -TargetOs $Settings.TargetOs -TargetCpu $Settings.TargetCpu

    $depotToolsCommit = Get-ShotFirstLine (& git -C $Settings.DepotTools rev-parse HEAD)

    $lock = [ordered]@{
        schema       = 'shot-bootstrap-input-lock/1'
        generatedUtc = (Get-Date).ToUniversalTime().ToString('o')
        chromium     = [ordered]@{
            commit    = $Settings.ChromiumCommit
            remote    = $Settings.ChromiumRemote
            reference = $reference
        }
        forkOverlay  = [ordered]@{
            enabled = -not $Settings.SkipForkOverlay
            ref     = $Settings.ForkRef
            commit  = $forkRef
            commits = $forkCommits
        }
        depotTools   = [ordered]@{
            path   = $Settings.DepotTools
            commit = $depotToolsCommit
            pinned = $Settings.DepotToolsCommit
            python = $Settings.Python
        }
        deps         = [ordered]@{
            path   = 'DEPS'
            sha256 = $deps.Sha256
            bytes  = $deps.Bytes
        }
        gclient      = [ordered]@{
            solutionName = $Settings.SolutionName
            url          = $Settings.ChromiumRemote
            depsFile     = 'DEPS'
            managed      = $false
            targetOs     = @($Settings.TargetOs)
            targetOsOnly = $true
            customVars   = $customVars
            customDeps   = @($customDeps.Paths)
            customDepsFile       = $customDeps.Path
            customDepsFileSha256 = $customDeps.Sha256
            contentSha256 = (Get-ShotStringSha256 -Text $gclientContent)
        }
        build        = [ordered]@{
            targetOs             = $Settings.TargetOs
            targetCpu            = $Settings.TargetCpu
            outDir               = $Settings.GnOutDir
            gnTarget             = $Settings.GnTarget
            argsTemplate         = $Settings.GnArgsTemplate
            argsTemplateSha256   = $gnArgsBlob.Sha256
            argsTemplateCommit   = $argsSourceCommit
            argsGnContent        = $argsGnContent
            argsGnSha256         = (Get-ShotStringSha256 -Text $argsGnContent)
        }
        hooks        = [ordered]@{
            total    = $evaluation.hookCount
            selected = $evaluation.selectedHookCount
            entries  = @($evaluation.hooks | Where-Object { $_.selected } | ForEach-Object {
                [ordered]@{ order = $_.order; name = $_.name; pattern = $_.pattern
                            condition = $_.condition; action = $_.action; actionSha256 = $_.actionSha256 }
            })
        }
        depsSummary  = $evaluation.summary
        baselineMatrix = $evaluation.baselineMatrix
    }

    # The per-dependency table is large (447 entries with CIPD versions and GCS
    # object hashes). It is the raw material for the Phase 2 lock files, so it
    # is available on request rather than by default.
    if ($Settings.IncludeDeps) {
        $lock['depsEntries'] = @($evaluation.deps)
    }

    # The digest deliberately covers only the inputs that decide what gets
    # fetched and built. Timestamps and paths are excluded so re-running the
    # same configuration resumes instead of refusing.
    $digestInput = [ordered]@{
        chromiumCommit   = $lock.chromium.commit
        chromiumRemote   = $lock.chromium.remote
        forkOverlay      = @{ enabled = $lock.forkOverlay.enabled; commit = $lock.forkOverlay.commit }
        depotToolsCommit = $lock.depotTools.commit
        depsSha256       = $lock.deps.sha256
        gclientSha256    = $lock.gclient.contentSha256
        customDepsSha256 = $lock.gclient.customDepsFileSha256
        argsGnSha256     = $lock.build.argsGnSha256
        argsTemplateSha256 = $lock.build.argsTemplateSha256
        targetOs         = $lock.build.targetOs
        targetCpu        = $lock.build.targetCpu
        hookActions      = @($lock.hooks.entries | ForEach-Object { $_.actionSha256 })
    }
    $lock['inputDigest'] = Get-ShotInputDigest $digestInput
    $lock['inputDigestInput'] = $digestInput

    [pscustomobject]$lock
}

function Assert-ShotCheckoutMatchesLock {
    <#
    .SYNOPSIS
        Re-verifies a materialised checkout against the Phase 0 lock.
    .DESCRIPTION
        Phase 0 reads facts from a reference checkout; Phase 1 has to prove the
        freshly cloned tree carries the same ones before any dependency is
        fetched against it.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]$Context,
        [Parameter(Mandatory)]$Lock,
        [Parameter(Mandatory)][string]$SrcRoot,
        [switch]$ExpectForkOverlay
    )

    $problems = [System.Collections.ArrayList]::new()

    $head = Get-ShotFirstLine (& git -C $SrcRoot rev-parse HEAD 2>$null)
    $expected = if ($ExpectForkOverlay -and $Lock.forkOverlay.enabled) { $Lock.forkOverlay.commit } else { $Lock.chromium.commit }
    if ($ExpectForkOverlay -and $Lock.forkOverlay.enabled) {
        # git am rewrites commit hashes (new committer/date), so the overlay tip
        # cannot be compared by hash. Ancestry of the pin is what matters.
        & git -C $SrcRoot merge-base --is-ancestor $Lock.chromium.commit HEAD 2>$null
        if ($LASTEXITCODE -ne 0) {
            [void]$problems.Add("HEAD ($head) does not descend from the pinned commit $($Lock.chromium.commit).")
        }
    } elseif ($head -ne $expected) {
        [void]$problems.Add("HEAD is $head, expected $expected.")
    }

    $depsPath = Join-Path $SrcRoot 'DEPS'
    if (-not (Test-Path -LiteralPath $depsPath)) {
        [void]$problems.Add("DEPS is missing from $SrcRoot.")
    } else {
        $sha = (Get-FileHash -LiteralPath $depsPath -Algorithm SHA256).Hash.ToLowerInvariant()
        if ($sha -ne $Lock.deps.sha256) {
            [void]$problems.Add("DEPS SHA-256 is $sha, expected $($Lock.deps.sha256). The checkout is not the pinned tree.")
        }
    }

    if ($ExpectForkOverlay -and $Lock.forkOverlay.enabled) {
        $templatePath = Join-Path $SrcRoot ($Lock.build.argsTemplate -replace '^//', '' -replace '/', '\')
        if (-not (Test-Path -LiteralPath $templatePath)) {
            [void]$problems.Add("GN args template $($Lock.build.argsTemplate) is missing after the overlay.")
        } else {
            $sha = (Get-FileHash -LiteralPath $templatePath -Algorithm SHA256).Hash.ToLowerInvariant()
            if ($sha -ne $Lock.build.argsTemplateSha256) {
                [void]$problems.Add("GN args template SHA-256 is $sha, expected $($Lock.build.argsTemplateSha256).")
            }
        }
    }

    if ($problems.Count -gt 0) {
        throw ("Checkout does not match the Phase 0 lock:`n  " + ($problems -join "`n  "))
    }
    Write-ShotLog -Context $Context -Level INFO -Message 'checkout matches the Phase 0 input lock.'
    $true
}

Export-ModuleMember -Function @(
    'Export-ShotGitBlob', 'Get-ShotGitBlobText', 'Read-ShotCustomDepsFile',
    'New-ShotGclientContent', 'New-ShotArgsGnContent', 'Invoke-ShotDepsEvaluation',
    'Assert-ShotDocBaseline', 'New-ShotInputLock', 'Assert-ShotCheckoutMatchesLock'
)
