# Copyright 2019 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Static data and public token types used by Blink.
source_set("clipboard_types") {
  sources = [
    "clipboard_constants.h",
    "clipboard_sequence_number_token.h",
  ]
  public_deps = [ "//base" ]
}
