# Copyright 2015 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("text_input_types") {
  sources = [
    "text_input_action.h",
    "text_input_flags.h",
    "text_input_mode.h",
    "text_input_type.h",
  ]
}

component("ime_types") {
  output_name = "ui_base_ime_types"
  sources = [
    "ime_text_span.cc",
    "ime_text_span.h",
    "text_edit_commands.h",
  ]

  defines = [ "IS_UI_BASE_IME_TYPES_IMPL" ]

  deps = [
    ":text_edit_commands",
    "//base",
    "//ui/gfx/geometry",
    "//ui/gfx/range",
  ]

  public_deps = [
    ":text_input_types",
    "//skia",
  ]
}

source_set("text_edit_commands") {
  sources = [ "text_edit_commands.inc" ]
}
