// Copyright 2015 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef NET_BASE_NET_ERROR_DETAILS_H_
#define NET_BASE_NET_ERROR_DETAILS_H_

#include "net/base/net_export.h"
#include "net/http/http_connection_info.h"

namespace net {

// A record of net errors with granular error specification generated by
// net stack.
//
// Everything this struct used to carry was QUIC's: the connection error code,
// the close source, whether the alternative services were marked broken, and
// the three connection-migration bits. HTTP/3 is out of this build, so what is
// left is the connection-type prediction, which HTTP/1.1 and HTTP/2 both set.
struct NET_EXPORT NetErrorDetails {
  NetErrorDetails() = default;

  // Early prediction of the connection type that this request attempts to use.
  // Will be discarded by upper layers if the connection type can be fetched
  // from response header from the server.
  HttpConnectionInfo connection_info = HttpConnectionInfo::kUNKNOWN;
};

}  // namespace net

#endif  // NET_BASE_NET_ERROR_DETAILS_H_
