import {createHash} from 'node:crypto';
import {closeSync, copyFileSync, existsSync, mkdirSync, openSync, readSync, statSync, utimesSync} from 'node:fs';
import path from 'node:path';

import {type DepsRecord, type LogEntry, toNinjaTime} from './ninja-state.ts';

// The coordinator stamps its own inputs. These manifests belong to its full
// build cache, not to a worker's delta of compiled outputs.
export const CI_INPUT_STATE = [
  'ci-input-mtimes.json', 'ci-runtime-feature-inputs.json', 'ci-source-inputs.json',
];

export interface OutputState {
  entry: LogEntry | undefined;
  deps: DepsRecord | undefined;
}

const mtimeNs = (file: string): bigint => statSync(file, {bigint: true}).mtimeNs;

function hashFile(file: string): string {
  const hash = createHash('sha256');
  const buffer = Buffer.allocUnsafe(64 * 1024);
  const fd = openSync(file, 'r');
  try {
    for (;;) {
      const size = readSync(fd, buffer, 0, buffer.length, null);
      if (!size) break;
      hash.update(buffer.subarray(0, size));
    }
  } finally { closeSync(fd); }
  return hash.digest('hex');
}

export function mergeShardOutput(
  from: string, to: string, source: OutputState, target: OutputState, preferOlderInput: boolean,
): OutputState & {copied: boolean} {
  const fromTime = mtimeNs(from);
  const present = existsSync(to);
  const toTime = present ? mtimeNs(to) : 0n;
  const compatible = source.entry
    ? target.entry?.hash === source.entry.hash
    : target.entry === undefined;
  // Only identical generated inputs may keep the older physical mtime, so
  // consumers built by other workers do not all become dirty. An old cached
  // object is not interchangeable with a fresh object merely because their
  // command hashes match: source bytes may have changed without new flags.
  const identical = present && compatible && preferOlderInput
    && statSync(from).size === statSync(to).size && hashFile(from) === hashFile(to);
  const keep = present && compatible && (identical ? toTime <= fromTime : toTime > fromTime);
  if (keep && !identical) return {...target, copied: false};

  let physicalTime = toTime;
  if (!keep) {
    mkdirSync(path.dirname(to), {recursive: true});
    copyFileSync(from, to);
    const seconds = Number(fromTime / 1000000000n) + Number(fromTime % 1000000000n) / 1e9;
    utimesSync(to, seconds, seconds);
    physicalTime = mtimeNs(to);  // utimes cannot represent every nanosecond.
  }

  // Ninja's build log records validation/command-start time, whereas the
  // deps log records physical output mtime. Do not overwrite both with one
  // timestamp. Identical generated bytes may reuse their older file but must
  // retain the newest successful validation and its matching dependency list.
  const entry = identical && target.entry && source.entry && target.entry.mtime > source.entry.mtime
    ? target.entry : source.entry;
  const record = entry && entry === target.entry ? target.deps : source.deps;
  return {
    copied: !keep,
    entry,
    deps: entry && record ? {mtime: toNinjaTime(physicalTime), deps: record.deps} : undefined,
  };
}
