import assert from 'node:assert/strict';
import {mkdtempSync, readFileSync, rmSync, statSync, utimesSync, writeFileSync} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test, {type TestContext} from 'node:test';

import {toNinjaTime} from './ninja-state.ts';
import {CI_INPUT_STATE, mergeShardOutput, type OutputState} from './shard-output.ts';

function fixture(t: TestContext, oldText = 'old', newText = 'new') {
  const dir = mkdtempSync(path.join(os.tmpdir(), 'shot-shard-output-'));
  t.after(() => rmSync(dir, {recursive: true, force: true}));
  const to = path.join(dir, 'target');
  const from = path.join(dir, 'shard');
  writeFileSync(to, oldText);
  writeFileSync(from, newText);
  utimesSync(to, 1000, 1000);
  utimesSync(from, 2000, 2000);
  return {to, from};
}

function state(when: number, header: string, hash = 'same-command'): OutputState {
  const time = toNinjaTime(BigInt(when) * 1000000000n);
  return {
    entry: {output: 'output', start: 0, end: 1, mtime: time, hash},
    deps: {mtime: time, deps: [header]},
  };
}

const physical = (file: string): bigint => toNinjaTime(statSync(file, {bigint: true}).mtimeNs);

test('shard output: a fresh object replaces a stale object with the same command hash', (t) => {
  const {from, to} = fixture(t);
  const incoming = state(1900, 'new.h');
  const result = mergeShardOutput(from, to, incoming, state(900, 'old.h'), false);
  assert.equal(result.copied, true);
  assert.equal(readFileSync(to, 'utf8'), 'new');
  assert.deepEqual(result.entry, incoming.entry);
  assert.deepEqual(result.deps, {mtime: physical(to), deps: ['new.h']});
});

test('shard output: compiled bytes that happen to match still receive fresh deps and time', (t) => {
  const {from, to} = fixture(t, 'same', 'same');
  const result = mergeShardOutput(from, to, state(1900, 'new.h'), state(900, 'old.h'), false);
  assert.equal(result.copied, true);
  assert.ok(statSync(to).mtimeMs > 1900000);
  assert.deepEqual(result.deps?.deps, ['new.h']);
});

test('shard output: an older differing worker copy cannot replace a newer object', (t) => {
  const {from, to} = fixture(t);
  utimesSync(to, 3000, 3000);
  const target = state(2900, 'keep.h');
  const result = mergeShardOutput(from, to, state(1900, 'old.h'), target, false);
  assert.equal(result.copied, false);
  assert.equal(readFileSync(to, 'utf8'), 'old');
  assert.deepEqual(result.entry, target.entry);
  assert.deepEqual(result.deps, target.deps);
});

test('shard output: a command change replaces the old producer regardless of its date', (t) => {
  const {from, to} = fixture(t);
  utimesSync(to, 3000, 3000);
  const incoming = state(1900, 'new.h', 'new-command');
  const result = mergeShardOutput(from, to, incoming, state(2900, 'old.h'), false);
  assert.equal(result.copied, true);
  assert.deepEqual(result.entry, incoming.entry);
});

test('shard output: a log entry without its physical file never suppresses a copy', (t) => {
  const {from, to} = fixture(t);
  rmSync(to);
  const result = mergeShardOutput(from, to, state(1900, 'new.h'), state(900, 'old.h'), false);
  assert.equal(result.copied, true);
  assert.equal(readFileSync(to, 'utf8'), 'new');
});

test('shard output: an unproven local file cannot beat a logged worker output', (t) => {
  const {from, to} = fixture(t);
  utimesSync(to, 3000, 3000);
  const result = mergeShardOutput(from, to, state(1900, 'new.h'), {entry: undefined, deps: undefined}, false);
  assert.equal(result.copied, true);
});

test('shard output: identical generated bytes keep old physical time and newest validation', (t) => {
  const {from, to} = fixture(t, 'same header', 'same header');
  const time = physical(to);
  const incoming = state(1900, 'new-generator.py');
  const result = mergeShardOutput(from, to, incoming, state(900, 'old-generator.py'), true);
  assert.equal(result.copied, false);
  assert.equal(physical(to), time);
  assert.deepEqual(result.entry, incoming.entry);
  assert.deepEqual(result.deps, {mtime: time, deps: ['new-generator.py']});
});

test('shard output: an older identical header preserves the newer local validation', (t) => {
  const {from, to} = fixture(t, 'same header', 'same header');
  utimesSync(from, 500, 500);
  const target = state(900, 'new-generator.py');
  const result = mergeShardOutput(from, to, state(400, 'old-generator.py'), target, true);
  assert.equal(result.copied, true);
  assert.deepEqual(result.entry, target.entry);
  assert.deepEqual(result.deps, {mtime: physical(to), deps: ['new-generator.py']});
  assert.ok(statSync(to).mtimeMs < 600000);
});

test('shard output: equal-sized changed generated bytes must replace an old header', (t) => {
  const {from, to} = fixture(t, 'AAA', 'BBB');
  const result = mergeShardOutput(from, to, state(1900, 'new.h'), state(900, 'old.h'), true);
  assert.equal(result.copied, true);
  assert.equal(readFileSync(to, 'utf8'), 'BBB');
});

test('shard output: Ninja validation time is not rewritten to physical output time', (t) => {
  const {from, to} = fixture(t);
  const incoming = state(1900, 'new.h');
  const result = mergeShardOutput(from, to, incoming, state(900, 'old.h'), false);
  assert.equal(result.entry?.mtime, incoming.entry?.mtime);
  assert.equal(result.deps?.mtime, physical(to));
  assert.notEqual(result.entry?.mtime, result.deps?.mtime);
  assert.ok(Math.abs(statSync(to).mtimeMs - 2000000) < 0.01);
});

test('shard output: replacing a producer without deps discards the old dependency list', (t) => {
  const {from, to} = fixture(t);
  const incoming = state(1900, 'unused');
  incoming.deps = undefined;
  const result = mergeShardOutput(from, to, incoming, state(900, 'old.h'), false);
  assert.equal(result.copied, true);
  assert.equal(result.deps, undefined);
});

test('shard output: unlogged GN files compare contents before retaining an older copy', (t) => {
  const {from, to} = fixture(t);
  const empty = {entry: undefined, deps: undefined};
  const result = mergeShardOutput(from, to, empty, empty, true);
  assert.equal(result.copied, true);
  assert.equal(readFileSync(to, 'utf8'), 'new');
  assert.equal(result.entry, undefined);
});

test('shard output: an object/archive pair remains ordered when preferring fresh binaries', (t) => {
  const {from, to} = fixture(t, 'object', 'object');
  const fromLib = from + '.a';
  const toLib = to + '.a';
  writeFileSync(fromLib, 'archive');
  writeFileSync(toLib, 'archive');
  utimesSync(fromLib, 2001, 2001);
  utimesSync(toLib, 1001, 1001);
  mergeShardOutput(from, to, state(1900, 'in.cc'), state(900, 'in.cc'), false);
  mergeShardOutput(fromLib, toLib, state(2000, 'object'), state(1000, 'object'), false);
  assert.ok(statSync(to).mtimeMs < statSync(toLib).mtimeMs);
});

test('shard output: source timestamp manifests belong to the coordinator, not shard deltas', () => {
  assert.deepEqual(CI_INPUT_STATE, [
    'ci-input-mtimes.json', 'ci-runtime-feature-inputs.json', 'ci-source-inputs.json',
  ]);
});
