# Copyright 2014 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

static_library("dom_keycode_converter") {
  public = [
    "keycodes/dom/dom_code.h",
    "keycodes/dom/dom_key.h",
    "keycodes/dom/keycode_converter.h",
  ]

  sources = [
    "keycodes/dom/dom_code_data.inc",
    "keycodes/dom/dom_key_data.inc",
    "keycodes/dom/keycode_converter.cc",
  ]

  deps = [ "//base" ]
}

source_set("event_constants") {
  sources = [ "event_constants.h" ]
}

component("events_base") {
  sources = [
    "base_event_utils.cc",
    "base_event_utils.h",
    "event_latency_metadata.h",
    "event_switches.cc",
    "event_switches.h",
    "events_base_export.h",
    "keycodes/keyboard_codes.h",
  ]

  if (is_win) {
    sources += [
      "keycodes/keyboard_codes_win.h",
      "keycodes/keyboard_defines_win.h",
    ]
  }

  defines = [ "EVENTS_BASE_IMPLEMENTATION" ]

  public_deps = [
    ":event_constants",
    "//base",
    "//ui/events/types:headers",
    "//ui/gfx/geometry",
  ]

}
