// Phase 0 input lock.
//
// What has to be recorded and verified before anything is fetched: Chromium
// commit, depot_tools commit, DEPS SHA-256, .gclient custom_vars/custom_deps,
// target_os/target_cpu, the GN args and their SHA-256, and the hook names,
// order and actions. This module builds that document from read-only
// inspection of a reference checkout and the pinned depot_tools, and
// re-verifies it against a materialised checkout in Phase 1.
//
// Nothing here touches the network or writes to the reference checkout.

import {createHash} from 'node:crypto';
import {existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync} from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import {execaSync} from 'execa';
import {z} from 'zod';

import {depsLock, type DepsSummary} from '../../deps-lock.ts';
import {firstLine, gitRead, inputDigest, log, sha256File, sha256Text, type RunContext} from './core.ts';

export interface Settings {
  chromiumCommit: string;
  chromiumRemote: string;
  depotTools: string;
  depotToolsCommit: string;
  referenceCheckout: string;
  forkRef: string;
  skipForkOverlay: boolean;
  solutionName: string;
  customDepsFile: string;
  checkoutConfiguration: string;
  targetOs: string;
  targetCpu: string;
  gnArgsTemplate: string;
  gnOutDir: string;
  gnTarget: string;
  syncJobs: number;
  minimumFreeGiB: number;
  allowNonEmpty: boolean;
  allowAncestorGclient: boolean;
  allowDepotToolsDrift: boolean;
  allowMissingSdk: boolean;
  skipSync: boolean;
  skipHooks: boolean;
  skipGnGen: boolean;
  includeDeps: boolean;
  python: string;
}

// Writes one blob from a pinned commit to a file, byte for byte: DEPS is
// hashed, and re-encoding the stream would change the SHA-256.
export function exportGitBlob(repo: string, commit: string, blobPath: string, outFile: string): string {
  const r = execaSync('git', ['-C', repo, 'cat-file', 'blob', `${commit}:${blobPath}`], {reject: false, encoding: 'buffer', stripFinalNewline: false, maxBuffer: 1 << 28});
  if (r.exitCode !== 0) throw new Error(`git cat-file blob ${commit}:${blobPath} failed in ${repo}: ${Buffer.from(r.stderr).toString('utf8')}`);
  writeFileSync(outFile, r.stdout);
  return outFile;
}

export interface BlobText {
  Path: string;
  Bytes: number;
  Sha256: string;
  Text: string;
}

export function gitBlobText(repo: string, commit: string, blobPath: string, allowMissing = false): BlobText | null {
  const r = execaSync('git', ['-C', repo, 'cat-file', 'blob', `${commit}:${blobPath}`], {reject: false, encoding: 'buffer', stripFinalNewline: false, maxBuffer: 1 << 28});
  if (r.exitCode !== 0) {
    if (allowMissing) return null;
    throw new Error(`git cat-file blob ${commit}:${blobPath} failed in ${repo}: ${Buffer.from(r.stderr).toString('utf8')}`);
  }
  const bytes = Buffer.from(r.stdout);
  return {Path: blobPath, Bytes: bytes.length, Sha256: createHash('sha256').update(bytes).digest('hex'), Text: bytes.toString('utf8')};
}

export interface CustomDepsFile {
  Path: string;
  Sha256: string;
  Paths: string[];
  Count: number;
}

export function readCustomDepsFile(file: string): CustomDepsFile {
  if (!existsSync(file)) throw new Error(`custom_deps batch file not found: ${file}`);
  const paths = readFileSync(file, 'utf8').split(/\r?\n/).map((l) => l.split('#', 1)[0].trim()).filter(Boolean);
  const seen = new Set<string>();
  const duplicates = paths.filter((p) => seen.size === seen.add(p).size);
  if (duplicates.length) throw new Error(`Duplicate entries in ${file}: ${[...new Set(duplicates)].join(', ')}`);
  for (const p of paths) {
    // Every DEPS key is rooted at the solution name. A path missing the
    // prefix silently matches nothing and would look like a saving that
    // never happened.
    if (!p.startsWith('src/')) throw new Error(`custom_deps entry must start with 'src/': '${p}' in ${file}`);
  }
  return {Path: file, Sha256: sha256File(file), Paths: paths, Count: paths.length};
}

// Renders the .gclient for the isolated target.
export function gclientContent(solutionName: string, url: string, customVars: Record<string, unknown>, customDeps: string[], targetOs: string): string {
  const lines = [
    '# Generated by scripts/bootstrap.ts. Do not hand-edit.',
    '#',
    '# The solution is named "src" and sits one level below this file because',
    '# every DEPS key is written as "src/...". managed = False keeps gclient from',
    '# moving the pinned commit underneath us.',
    'solutions = [',
    '  {',
    `    "name"      : '${solutionName}',`,
    `    "url"       : '${url}',`,
    `    "deps_file" : 'DEPS',`,
    '    "managed"   : False,',
    '    "custom_deps" : {',
    ...customDeps.map((d) => `      '${d}': None,`),
    '    },',
    '    "custom_vars": {',
    ...Object.keys(customVars).sort().map((k) => {
      const v = customVars[k];
      return `      '${k}': ${typeof v === 'boolean' ? (v ? 'True' : 'False') : `'${v}'`},`;
    }),
    '    },',
    '  },',
    ']',
    '',
    `target_os = ['${targetOs}']`,
    'target_os_only = True',
  ];
  // LF on every platform. The PowerShell version used Environment.NewLine,
  // which made the lock digest depend on the host that computed it.
  return lines.join('\n') + '\n';
}

// Renders out/<dir>/args.gn. target_os and target_cpu are written explicitly
// even though they match the host default: they are locked inputs, and a
// lock that relies on host detection is not a lock.
export function argsGnContent(template: string, targetOs: string, targetCpu: string): string {
  return ['# Generated by scripts/bootstrap.ts. Do not hand-edit.', `import("${template}")`, `target_os = "${targetOs}"`, `target_cpu = "${targetCpu}"`, ''].join('\n');
}

// Numbers pinned for the baseline DEPS. If the evaluator disagrees, either
// DEPS is not the pinned one, depot_tools drifted, or the candidate batch was
// edited. All three invalidate the lock, so this is an error rather than a
// note.
const DOC_BASELINE: Record<string, Partial<DepsSummary>> = {
  'default': {remaining: 187, git: 139, cipd: 33, gcs: 15},
  'small': {remaining: 180, git: 132, cipd: 33, gcs: 15},
  'small+null': {remaining: 133, git: 115, cipd: 11, gcs: 7},
};

export function assertDocBaseline(matrix: Record<string, DepsSummary>): void {
  const problems: string[] = [];
  for (const [label, expected] of Object.entries(DOC_BASELINE)) {
    const actual = matrix[label];
    if (!actual) {
      problems.push(`missing row '${label}'`);
      continue;
    }
    for (const [field, value] of Object.entries(expected)) {
      if (actual[field as keyof DepsSummary] !== value) problems.push(`${label}.${field} expected ${value} got ${actual[field as keyof DepsSummary]}`);
    }
  }
  if (problems.length) throw new Error(`DEPS evaluation does not match the pinned baseline:\n  ${problems.join('\n  ')}`);
}

// The lock as written to input-lock.json, validated with zod when read back
// on a resumed run so a hand-edited or truncated file is refused with a
// message that names the field.
export const LockSchema = z.object({
  schema: z.literal('shot-bootstrap-input-lock/1'),
  generatedUtc: z.string(),
  chromium: z.object({commit: z.string(), remote: z.string(), reference: z.string()}),
  forkOverlay: z.object({enabled: z.boolean(), ref: z.string(), commit: z.string().nullable(), commits: z.array(z.object({commit: z.string(), subject: z.string(), files: z.array(z.string())}))}),
  depotTools: z.object({path: z.string(), commit: z.string(), pinned: z.string(), python: z.string()}),
  deps: z.object({path: z.string(), sha256: z.string(), bytes: z.number()}),
  gclient: z.object({
    solutionName: z.string(), url: z.string(), depsFile: z.string(), managed: z.boolean(), targetOs: z.array(z.string()), targetOsOnly: z.boolean(),
    customVars: z.record(z.string(), z.unknown()), customDeps: z.array(z.string()), customDepsFile: z.string(), customDepsFileSha256: z.string(), contentSha256: z.string(),
  }),
  build: z.object({targetOs: z.string(), targetCpu: z.string(), outDir: z.string(), gnTarget: z.string(), argsTemplate: z.string(), argsTemplateSha256: z.string(), argsTemplateCommit: z.string(), argsGnContent: z.string(), argsGnSha256: z.string()}),
  hooks: z.object({total: z.number(), selected: z.number(), entries: z.array(z.object({order: z.number(), name: z.string().nullable(), pattern: z.string().nullable(), condition: z.string().nullable(), action: z.array(z.string()), actionSha256: z.string()}))}),
  depsSummary: z.record(z.string(), z.unknown()),
  baselineMatrix: z.record(z.string(), z.unknown()),
  depsEntries: z.array(z.unknown()).optional(),
  inputDigest: z.string(),
  inputDigestInput: z.record(z.string(), z.unknown()),
});
export type Lock = z.infer<typeof LockSchema>;

// Builds the Phase 0 lock document from read-only inputs.
export function newInputLock(ctx: RunContext, s: Settings): Lock {
  const reference = s.referenceCheckout;
  if (!reference || !existsSync(path.join(reference, '.git'))) throw new Error(`A reference checkout is required to build the input lock; '${reference}' is not a git repository.`);
  // The pinned commit must actually be reachable in the reference checkout,
  // otherwise the DEPS and hook facts below would describe a different tree.
  if (gitRead(reference, ['cat-file', '-e', `${s.chromiumCommit}^{commit}`], true).exitCode !== 0) {
    throw new Error(`Pinned Chromium commit ${s.chromiumCommit} is not present in the reference checkout ${reference}.`);
  }
  let forkRef: string | null = null;
  let forkCommits: Lock['forkOverlay']['commits'] = [];
  if (!s.skipForkOverlay) {
    const r = gitRead(reference, ['rev-parse', `${s.forkRef}^{commit}`], true);
    forkRef = firstLine(r.output);
    if (r.exitCode !== 0 || !forkRef) throw new Error(`Fork overlay ref '${s.forkRef}' does not resolve in ${reference}.`);
    if (gitRead(reference, ['merge-base', '--is-ancestor', s.chromiumCommit, forkRef], true).exitCode !== 0) {
      throw new Error(`Fork ref ${forkRef} does not descend from the pinned commit ${s.chromiumCommit}; the overlay would not be a pure addition on top of the pin.`);
    }
    const logLines = gitRead(reference, ['log', '--reverse', '--format=%H%x1f%s', `${s.chromiumCommit}..${forkRef}`], true).output;
    forkCommits = logLines.filter(Boolean).map((line) => {
      const [commit, subject] = line.split('\x1f', 2);
      const files = gitRead(reference, ['diff-tree', '--no-commit-id', '--name-only', '-r', commit], true).output.filter(Boolean);
      return {commit, subject: subject ?? '', files};
    });
  }
  const deps = gitBlobText(reference, s.chromiumCommit, 'DEPS')!;
  // The GN args template lives in the fork, not upstream. Read it from the
  // overlay tip so the lock records what gn gen will actually import.
  const argsSourceCommit = forkRef ?? s.chromiumCommit;
  const gnArgsBlob = gitBlobText(reference, argsSourceCommit, s.gnArgsTemplate.replace(/^\/\//, ''), true);
  if (!gnArgsBlob) throw new Error(`GN args template '${s.gnArgsTemplate}' does not exist at ${argsSourceCommit} in ${reference}. Phase 1 would generate an args.gn that imports a missing file.`);

  const customDeps = readCustomDepsFile(s.customDepsFile);
  const customVars = {checkout_configuration: s.checkoutConfiguration};

  // The evaluation needs the DEPS blob on disk; keep it inside the run state
  // so the evaluated artefact and its inputs stay together.
  let depsCopy = path.join(ctx.stateRoot, 'DEPS.pinned');
  let temp: string | null = null;
  if (ctx.dryRun) {
    temp = mkdtempSync(path.join(os.tmpdir(), 'shot-deps-'));
    depsCopy = path.join(temp, 'DEPS.pinned');
    writeFileSync(depsCopy, deps.Text, 'utf8');
  } else {
    exportGitBlob(reference, s.chromiumCommit, 'DEPS', depsCopy);
  }
  let evaluation: Record<string, unknown>;
  try {
    evaluation = depsLock({depsFile: depsCopy, depotTools: s.depotTools, customDepsFile: s.customDepsFile, customVars, baselineMatrix: true, includeDeps: s.includeDeps, python: s.python});
  } finally {
    if (temp) rmSync(temp, {recursive: true, force: true});
  }
  if (evaluation.depsSha256 !== deps.Sha256) throw new Error(`DEPS hash mismatch between the git blob (${deps.Sha256}) and the evaluated copy (${evaluation.depsSha256}).`);
  assertDocBaseline(evaluation.baselineMatrix as Record<string, DepsSummary>);

  const gclient = gclientContent(s.solutionName, s.chromiumRemote, customVars, customDeps.Paths, s.targetOs);
  const argsGn = argsGnContent(s.gnArgsTemplate, s.targetOs, s.targetCpu);
  const depotToolsCommit = firstLine(gitRead(s.depotTools, ['rev-parse', 'HEAD']).output);
  const hooks = evaluation.hooks as Array<{order: number; name: string | null; pattern: string | null; condition: string | null; selected: boolean; action: string[]; actionSha256: string}>;

  const lock: Lock = {
    schema: 'shot-bootstrap-input-lock/1',
    generatedUtc: new Date().toISOString(),
    chromium: {commit: s.chromiumCommit, remote: s.chromiumRemote, reference},
    forkOverlay: {enabled: !s.skipForkOverlay, ref: s.forkRef, commit: forkRef, commits: forkCommits},
    depotTools: {path: s.depotTools, commit: depotToolsCommit, pinned: s.depotToolsCommit, python: s.python},
    deps: {path: 'DEPS', sha256: deps.Sha256, bytes: deps.Bytes},
    gclient: {
      solutionName: s.solutionName, url: s.chromiumRemote, depsFile: 'DEPS', managed: false, targetOs: [s.targetOs], targetOsOnly: true, customVars,
      customDeps: customDeps.Paths, customDepsFile: customDeps.Path, customDepsFileSha256: customDeps.Sha256, contentSha256: sha256Text(gclient),
    },
    build: {
      targetOs: s.targetOs, targetCpu: s.targetCpu, outDir: s.gnOutDir, gnTarget: s.gnTarget, argsTemplate: s.gnArgsTemplate, argsTemplateSha256: gnArgsBlob.Sha256,
      argsTemplateCommit: argsSourceCommit, argsGnContent: argsGn, argsGnSha256: sha256Text(argsGn),
    },
    hooks: {
      total: evaluation.hookCount as number,
      selected: evaluation.selectedHookCount as number,
      entries: hooks.filter((h) => h.selected).map((h) => ({order: h.order, name: h.name, pattern: h.pattern, condition: h.condition, action: h.action, actionSha256: h.actionSha256})),
    },
    depsSummary: evaluation.summary as Record<string, unknown>,
    baselineMatrix: evaluation.baselineMatrix as Record<string, unknown>,
    inputDigest: '',
    inputDigestInput: {},
  };
  // The per-dependency table is large. It is the raw material for later lock
  // files, so it is available on request rather than by default.
  if (s.includeDeps) lock.depsEntries = evaluation.deps as unknown[];
  // The digest deliberately covers only the inputs that decide what gets
  // fetched and built. Timestamps and paths are excluded so re-running the
  // same configuration resumes instead of refusing.
  const digestInput = {
    chromiumCommit: lock.chromium.commit,
    chromiumRemote: lock.chromium.remote,
    forkOverlay: {enabled: lock.forkOverlay.enabled, commit: lock.forkOverlay.commit},
    depotToolsCommit: lock.depotTools.commit,
    depsSha256: lock.deps.sha256,
    gclientSha256: lock.gclient.contentSha256,
    customDepsSha256: lock.gclient.customDepsFileSha256,
    argsGnSha256: lock.build.argsGnSha256,
    argsTemplateSha256: lock.build.argsTemplateSha256,
    targetOs: lock.build.targetOs,
    targetCpu: lock.build.targetCpu,
    hookActions: lock.hooks.entries.map((h) => h.actionSha256),
  };
  lock.inputDigest = inputDigest(digestInput);
  lock.inputDigestInput = digestInput;
  return lock;
}

// Re-verifies a materialised checkout against the Phase 0 lock: Phase 1 has
// to prove the freshly cloned tree carries the same facts before any
// dependency is fetched against it.
export function assertCheckoutMatchesLock(ctx: RunContext, lock: Lock, srcRoot: string, expectForkOverlay: boolean): void {
  const problems: string[] = [];
  const head = firstLine(gitRead(srcRoot, ['rev-parse', 'HEAD'], true).output);
  const overlay = expectForkOverlay && lock.forkOverlay.enabled;
  if (overlay) {
    // git am rewrites commit hashes (new committer/date), so the overlay tip
    // cannot be compared by hash. Ancestry of the pin is what matters.
    if (gitRead(srcRoot, ['merge-base', '--is-ancestor', lock.chromium.commit, 'HEAD'], true).exitCode !== 0) {
      problems.push(`HEAD (${head}) does not descend from the pinned commit ${lock.chromium.commit}.`);
    }
  } else if (head !== lock.chromium.commit) {
    problems.push(`HEAD is ${head}, expected ${lock.chromium.commit}.`);
  }
  const depsPath = path.join(srcRoot, 'DEPS');
  if (!existsSync(depsPath)) problems.push(`DEPS is missing from ${srcRoot}.`);
  else if (sha256File(depsPath) !== lock.deps.sha256) problems.push(`DEPS SHA-256 is ${sha256File(depsPath)}, expected ${lock.deps.sha256}. The checkout is not the pinned tree.`);
  if (overlay) {
    const templatePath = path.join(srcRoot, lock.build.argsTemplate.replace(/^\/\//, ''));
    if (!existsSync(templatePath)) problems.push(`GN args template ${lock.build.argsTemplate} is missing after the overlay.`);
    else if (sha256File(templatePath) !== lock.build.argsTemplateSha256) problems.push(`GN args template SHA-256 is ${sha256File(templatePath)}, expected ${lock.build.argsTemplateSha256}.`);
  }
  if (problems.length) throw new Error(`Checkout does not match the Phase 0 lock:\n  ${problems.join('\n  ')}`);
  log(ctx, 'INFO', 'checkout matches the Phase 0 input lock.');
}
