# Copyright 2017 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

component("metrics_cpp") {
  sources = [
    "delegating_ukm_recorder.cc",
    "delegating_ukm_recorder.h",
    "metrics_export.h",
    "metrics_utils.cc",
    "metrics_utils.h",
    "mojo_ukm_recorder.cc",
    "mojo_ukm_recorder.h",
    "ukm_entry_builder.cc",
    "ukm_entry_builder.h",
    "ukm_entry_builder_base.cc",
    "ukm_entry_builder_base.h",
    "ukm_recorder.cc",
    "ukm_recorder.h",
    "ukm_recorder_client_interface_registry.cc",
    "ukm_recorder_client_interface_registry.h",
    "ukm_recorder_impl_utils.cc",
    "ukm_recorder_impl_utils.h",
    "ukm_source.cc",
    "ukm_source.h",
    "ukm_source_id.cc",
    "ukm_source_id.h",
  ]

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  defines = [ "METRICS_IMPLEMENTATION" ]

  public_deps = [
    "//base",
    "//net",
    "//services/metrics/public/mojom",
    "//url",
  ]

  deps = [
    "//mojo/public/cpp/bindings",
    "//third_party/metrics_proto",
  ]
}
