"""Generate blink's V8<Enum> classes from the .idl files, without V8.

blink core does not use plain C++ enums for IDL enumerations. It uses the
classes the bindings generator emits -- V8AnimationPlayState, V8CompositeOperation,
V8FillMode -- as its own type vocabulary, all through core, css, animation and
layout:

    if (play_state == V8AnimationPlayState::Enum::kFinished)
    timing.fill_mode = V8FillMode(V8FillMode::Enum::kBackwards);

The generator lived in third_party/blink/renderer/bindings/scripts and is gone
with V8. The .idl files it read are not: 690 of them survive under
renderer/core alone, and they are the actual source of truth for the value
lists. So the classes can be regenerated from the same input, minus the parts
that only exist to talk to a JavaScript engine.

What is dropped relative to upstream's output:

  * Create(v8::Isolate*, v8::Local<v8::Value>, ExceptionState&) -- converts a JS
    value to the enum. There is no JS value to convert.
  * ToV8() / the NativeValueTraits and ToV8Traits specialisations.

What is kept is everything blink's own code uses: the Enum class, the string
table, construction from an Enum, AsEnum(), and the AsCStr()/AsString()/
comparison operators inherited from bindings::EnumerationBase.

The output is written into the source tree rather than into gen/. It is derived
from checked-in .idl files by a checked-in script, so it is reproducible either
way, and putting it in the tree keeps it out of the GN action graph -- which
matters because the target that would run it (blink_bindings_generator) is one
of the things that went away.

Usage:
  gen_idl_enums.py [-n] [--check]

  -n       dry run
  --check  verify that every V8Foo::Enum::kBar named in renderer/core and
           renderer/platform is actually produced. This is the real test: the
           call sites were written against upstream's generator, so agreeing
           with them is agreeing with it.
"""

import io
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RENDERER = os.path.join(ROOT, "third_party", "blink", "renderer")

# `enum Foo { "a", "b" };` -- IDL allows newlines and comments inside the body.
ENUM = re.compile(r"^\s*enum\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{(.*?)\}\s*;",
                  re.S | re.M)
VALUE = re.compile(r'"([^"]*)"')
COMMENT = re.compile(r"//[^\n]*")

HEADER = """// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// Generated by tools/shot/gen_idl_enums.py from %(idl)s.
// Do not edit; edit the .idl and re-run the generator.

#ifndef %(guard)s
#define %(guard)s

#include <array>

#include "third_party/blink/renderer/platform/bindings/enumeration_base.h"
#include "third_party/blink/renderer/platform/wtf/text/wtf_string.h"

namespace blink {

// IDL enumeration %(name)s.
class %(cls)s final : public bindings::EnumerationBase {
 public:
  enum class Enum : enum_int_t {
%(entries)s  };

  // std::array rather than a C array: indexing a raw array is
  // -Wunsafe-buffer-usage, which this tree builds with -Werror, and the index
  // below is a hard error in 590 translation units otherwise. std::array's
  // operator[] is a member function, so it is not caught by that warning and
  // is bounds-checked under libc++ hardening.
  static constexpr std::array<const char*, %(count)d> kEnumStrings = {
%(strings)s  };

  // Not explicit: upstream's generated class is implicitly constructible from
  // its Enum, and call sites rely on that (`return V8FillMode::Enum::kBoth;`).
  constexpr %(cls)s(Enum value)
      : bindings::EnumerationBase(static_cast<enum_int_t>(value),
                                  kEnumStrings[static_cast<enum_int_t>(value)]) {}

  constexpr %(cls)s(const %(cls)s&) = default;
  constexpr %(cls)s(%(cls)s&&) = default;
  %(cls)s& operator=(const %(cls)s&) = default;
  %(cls)s& operator=(%(cls)s&&) = default;
  ~%(cls)s() = default;

  Enum AsEnum() const { return static_cast<Enum>(GetEnumValue()); }

 private:
  // Only the generated Create() produced an empty instance, to represent
  // "an exception was thrown while converting". Nothing here throws.
  constexpr %(cls)s() = default;
};

}  // namespace blink

#endif  // %(guard)s
"""


def snake(name):
    """CamelCase -> snake_case, keeping acronym runs together (CSSBoxType ->
    css_box_type), which is how the bindings generator names its files."""
    out = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name)
    out = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", "_", out)
    return out.lower()


# Tokens the bindings generator's name_style_converter keeps fully upper-case
# instead of title-casing. Without these, "srgb-linear" comes out kSrgbLinear
# where every call site in core says kSRGBLinear. Only the ones that actually
# occur in the surviving .idl files are listed; --check is what proves the list
# is complete.
# The rule is not "upper-case every acronym": the call sites say kRgbaFloat16,
# kRec2100Hlg and kSharedStorageSelectUrl, so rgba, hlg and url are title-cased
# like any other word. srgb is the one token in the surviving .idl files that
# is not, which is why this table has exactly one entry. --check is what keeps
# it honest -- add to it only when a real call site disagrees.
ACRONYMS = {"srgb": "SRGB"}


def entry(value):
    """IDL enum string -> C++ enumerator name, matching upstream's spelling."""
    if value == "":
        # Bare "k". This looked like it should be "kEmptyString" and was, until
        # the call sites said otherwise: upstream's own vtt_region.h at the
        # pristine baseline reads
        #     V8ScrollSetting::Enum scroll_ = V8ScrollSetting::Enum::k;
        # and html_media_element.cc and vtt_cue.cc spell V8CanPlayTypeResult and
        # V8DirectionSetting the same way. There is not one use of
        # "Enum::kEmptyString" in the tree. The generator just appends "k" to the
        # camel-cased words of the value, and an empty value has none.
        return "k"
    parts = [p for p in re.split(r"[^A-Za-z0-9]+", value) if p]
    out = []
    for p in parts:
        if p.lower() in ACRONYMS:
            out.append(ACRONYMS[p.lower()])
        elif p[:2].isupper():
            # An already-capitalised run stays as written.
            out.append(p)
        else:
            out.append(p[:1].upper() + p[1:])
    return "k" + "".join(out)


def collect():
    """(enum name) -> (idl path, [values]). Later definitions must agree."""
    found = {}
    for dirpath, _dirs, files in os.walk(RENDERER):
        for name in files:
            if not name.endswith(".idl"):
                continue
            path = os.path.join(dirpath, name)
            src = io.open(path, encoding="utf-8", errors="replace").read()
            src = COMMENT.sub("", src)
            for m in ENUM.finditer(src):
                enum_name, body = m.group(1), m.group(2)
                values = VALUE.findall(body)
                if not values:
                    continue
                rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
                if enum_name in found and found[enum_name][1] != values:
                    print("  CONFLICT %s: %s vs %s"
                          % (enum_name, found[enum_name][0], rel))
                    continue
                found.setdefault(enum_name, (rel, values))
    return found


def out_dir_for(idl_rel):
    part = "modules" if "/renderer/modules/" in idl_rel else "core"
    return os.path.join(RENDERER, "bindings", part, "v8")


def main(argv):
    dry = "-n" in argv
    check = "--check" in argv

    found = collect()
    produced = set()
    written = 0
    for name, (idl_rel, values) in sorted(found.items()):
        cls = "V8" + name
        entries = [entry(v) for v in values]
        if len(set(entries)) != len(entries):
            print("  SKIP %s: enumerator collision %s" % (cls, entries))
            continue
        for e in entries:
            produced.add("%s::Enum::%s" % (cls, e))

        out_dir = out_dir_for(idl_rel)
        fname = "v8_%s.h" % snake(name)
        guard = ("THIRD_PARTY_BLINK_RENDERER_BINDINGS_%s_V8_V8_%s_H_"
                 % (os.path.basename(os.path.dirname(out_dir)).upper(),
                    snake(name).upper()))
        text = HEADER % {
            "idl": idl_rel,
            "guard": guard,
            "name": name,
            "cls": cls,
            "entries": "".join("    %s,\n" % e for e in entries),
            "strings": "".join('      "%s",\n' % v for v in values),
            "count": len(values),
        }
        if not dry:
            os.makedirs(out_dir, exist_ok=True)
            io.open(os.path.join(out_dir, fname), "w", encoding="utf-8",
                    newline="\n").write(text)
        written += 1

    print("%d IDL enums, %d headers written%s"
          % (len(found), written, " (dry run)" if dry else ""))

    if check:
        used = subprocess.run(
            ["git", "grep", "-ohE", r"\bV8[A-Za-z0-9_]+::Enum::k[A-Za-z0-9_]*",
             "--", "third_party/blink/renderer/core",
             "third_party/blink/renderer/platform"],
            cwd=ROOT, capture_output=True, text=True).stdout.split()
        missing = sorted(set(used) - produced)
        print("%d distinct enum values referenced, %d not produced"
              % (len(set(used)), len(missing)))
        for m in missing:
            print("    MISSING %s" % m)


if __name__ == "__main__":
    main(sys.argv[1:])
