"""Write the GN source list for the regenerated bindings.

gen_idl_enums.py, gen_idl_unions.py and gen_idl_dictionaries.py each emit into
third_party/blink/renderer/bindings/<component>/v8/. The unions and
dictionaries emit a .cc as well as a .h, because tracing a Member<T> needs T
complete and including T's header from the .h closes a cycle back through
v8_typedefs.h.

Those .cc files have to be compiled, so they need to be listed. Scanning the
directory rather than having each generator maintain its share of the list is
what keeps the three of them from disagreeing about it.

Run this after any of the three generators.

Usage:
  gen_idl_build_gni.py
"""

import io
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BINDINGS = os.path.join(ROOT, "third_party", "blink", "renderer", "bindings")

GNI = '''# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Generated by tools/shot/gen_idl_build_gni.py. Do not edit.
#
# The IDL enum, union and dictionary classes, regenerated without V8 by
# tools/shot/gen_idl_*.py. Upstream produced these from the same .idl files
# through third_party/blink/renderer/bindings/scripts, which went with V8.
#
# They are part of the core component rather than a target of their own: the
# .cc files include core headers (a union of (double or CSSNumericValue) traces
# a Member<CSSNumericValue>) and core includes these, so any other arrangement
# is a dependency cycle.
blink_core_sources_bindings_core_v8 = [
%s]
'''

BUILD = '''# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//third_party/blink/renderer/core/core.gni")
import("//third_party/blink/renderer/bindings/core/v8/build.gni")

blink_core_sources("bindings_core_v8") {
  sources = blink_core_sources_bindings_core_v8

  deps = [ "//third_party/blink/renderer/core:core_generated" ]
}
'''


def main():
    for component in ("core", "modules"):
        d = os.path.join(BINDINGS, component, "v8")
        if not os.path.isdir(d):
            continue
        names = sorted(n for n in os.listdir(d) if n.endswith((".cc", ".h")))
        if not any(n.endswith(".cc") for n in names):
            continue
        io.open(os.path.join(d, "build.gni"), "w", encoding="utf-8",
                newline="\n").write(
                    GNI % "".join('  "%s",\n' % n for n in names))
        io.open(os.path.join(d, "BUILD.gn"), "w", encoding="utf-8",
                newline="\n").write(BUILD.replace("core/v8", component + "/v8")
                                    .replace("bindings_core_v8",
                                             "bindings_%s_v8" % component))
        print("  %s/v8: %d sources" % (component, len(names)))


if __name__ == "__main__":
    main()
