"""Delete generated binding files whose source .idl is gone.

The three generators (gen_idl_enums.py, gen_idl_unions.py,
gen_idl_dictionaries.py) write into
third_party/blink/renderer/bindings/<component>/v8/ and never remove anything.
That is fine while .idl files only ever get added, and wrong the moment a cut
wave deletes one: the generated .h/.cc stay behind, keep their entry in
build.gni, and are compiled. Sometimes they even still compile -- an enum class
with no callers does -- and sometimes they do not, because they name a blink
class that went with the .idl. Either way they are dead weight in the binary.

Every generated file carries the line

    // Generated by tools/shot/gen_idl_unions.py from <path>.idl.

so the question "does this file still have an input?" is answerable from the
file itself rather than by re-deriving the generators' naming rules. A union is
named after its members, not after one .idl, so a union file cites the .idl it
was first seen in; when that .idl is deleted but the union is still reachable
from another one, the next generator run rewrites the file and the citation
moves. That is why this runs *after* the generators, not before: anything still
wanted has just been written, and only genuine orphans are left pointing at a
path that no longer exists.

Usage:
  gen_idl_prune.py [-n]
"""

import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BINDINGS = os.path.join(ROOT, "third_party", "blink", "renderer", "bindings")
FROM = re.compile(r"^// Generated by tools/shot/(\S+) from (\S+?)\.$", re.M)


def main(argv):
    dry = "-n" in argv
    orphans = []
    scanned = 0
    for component in sorted(os.listdir(BINDINGS)):
        d = os.path.join(BINDINGS, component, "v8")
        if not os.path.isdir(d):
            continue
        for name in sorted(os.listdir(d)):
            if not name.endswith(".h"):
                continue
            path = os.path.join(d, name)
            head = io.open(path, encoding="utf-8", newline="").read(2048)
            m = FROM.search(head)
            if not m:
                continue  # hand-written, or v8_typedefs.h
            scanned += 1
            src = os.path.join(ROOT, m.group(2).replace("/", os.sep))
            if os.path.exists(src):
                continue
            orphans.append((path, m.group(2)))

    for path, src in orphans:
        rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
        print("  orphan %-72s (from %s)" % (rel, src))
        if dry:
            continue
        os.remove(path)
        impl = path[:-2] + ".cc"
        if os.path.exists(impl):
            os.remove(impl)

    print("%d generated headers scanned, %d orphaned%s"
          % (scanned, len(orphans), " (dry run)" if dry else " and deleted"))
    print("Re-run gen_idl_build_gni.py to drop them from build.gni.")


if __name__ == "__main__":
    main(sys.argv[1:])
