"""Run the three IDL generators, delete what they no longer produce, rewrite build.gni.

The generators only ever write. That is fine while .idl files accumulate and
wrong the moment a cut wave deletes one or edits an attribute away: the .h/.cc
stay behind, keep their build.gni entry, and get compiled. Sometimes they even
compile -- an enum class with no callers does -- and sit in the binary; sometimes
they name a blink class that went with the .idl and the build stops in a
generated file nobody edited.

gen_idl_prune.py answers "does this file's source .idl still exist?", which
catches a deleted .idl but not an *edited* one. When
core/html/html_script_element.idl stopped declaring

    attribute (TrustedScriptURL or USVString) src;

the .idl was still there, so v8_union_trustedscripturl_usvstring.{h,cc} survived
the prune while no longer being produced by anything.

The criterion used here is exact instead: every generator rewrites all of its
outputs on every run, so **a generated file not touched during this run is not
produced any more**. Record the time, run all three, delete what is older.

This is the entry point to use after any .idl changes. The individual
generators remain runnable on their own for iterating on one of them.

Usage:
  gen_idl_all.py [-n]
"""

import io
import os
import re
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
BINDINGS = os.path.join(ROOT, "third_party", "blink", "renderer", "bindings")
BANNER = re.compile(r"^// Generated by tools/shot/(\S+) from ", re.M)
GENERATORS = ["gen_idl_enums.py", "gen_idl_unions.py", "gen_idl_dictionaries.py"]


def generated_files():
    """Every .h under bindings/*/v8 carrying a generator banner."""
    out = []
    for component in sorted(os.listdir(BINDINGS)):
        d = os.path.join(BINDINGS, component, "v8")
        if not os.path.isdir(d):
            continue
        for name in sorted(os.listdir(d)):
            if not name.endswith(".h"):
                continue
            path = os.path.join(d, name)
            if BANNER.search(io.open(path, encoding="utf-8",
                                     newline="").read(2048)):
                out.append(path)
    return out


def main(argv):
    dry = "-n" in argv

    # A whole second of slack: the filesystem timestamp granularity is coarser
    # than this loop, and a file rewritten with identical content still gets a
    # fresh mtime, so the margin only has to cover the clock, not the work.
    start = time.time() - 1.0

    for gen in GENERATORS:
        print("== %s" % gen)
        args = [sys.executable, os.path.join(HERE, gen)]
        if dry:
            args.append("-n")
        r = subprocess.run(args, cwd=ROOT)
        if r.returncode != 0:
            sys.exit("%s failed (%d)" % (gen, r.returncode))

    if dry:
        print("== dry run: not pruning, not rewriting build.gni")
        return

    print("== prune")
    stale = [p for p in generated_files() if os.path.getmtime(p) < start]
    for path in stale:
        rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
        print("  stale  %s" % rel)
        os.remove(path)
        impl = path[:-2] + ".cc"
        if os.path.exists(impl):
            os.remove(impl)
    print("  %d generated header(s) no longer produced" % len(stale))

    print("== build.gni")
    subprocess.run([sys.executable, os.path.join(HERE, "gen_idl_build_gni.py")],
                   cwd=ROOT, check=True)


if __name__ == "__main__":
    main(sys.argv[1:])
