# Copyright 2017 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/buildflag_header.gni")
import("//build/config/shot_build.gni")
import("//net/features.gni")
import("//services/network/public/cpp/features.gni")
import("//third_party/blink/renderer/build/scripts/scripts.gni")  # TODO(crbug.com/397934758)

_is_directory_transfer_required = is_fuchsia
buildflag_header("buildflags") {
  header = "network_service_buildflags.h"
  flags = [
    "IS_CT_SUPPORTED=$is_ct_supported",
    "IS_P2P_ENABLED=$is_p2p_enabled",
    "IS_DIRECTORY_TRANSFER_REQUIRED=$_is_directory_transfer_required",
  ]
}

# TODO(crbug.com/397934758): Move `blink_python_runner` out of Blink and update
# this action.
blink_python_runner("make_generated_permissions_policy_features") {
  script =
      "//services/network/build/scripts/make_permissions_policy_features.py"

  inputs = scripts_for_json5_files + [
             "//services/network/build/scripts/make_permissions_policy_features.py",
             "//services/network/public/cpp/permissions_policy/permissions_policy_features.json5",
             "//services/network/build/scripts/templates/permissions_policy_features_generated.cc.tmpl",
           ]
  outputs = [ "$root_gen_dir/services/network/public/cpp/permissions_policy/permissions_policy_features_generated.cc" ]

  args = [
    rebase_path(
        "//services/network/public/cpp/permissions_policy/permissions_policy_features.json5",
        root_build_dir),
    "--output_dir",
    rebase_path("$root_gen_dir/services/network/public/cpp/permissions_policy",
                root_build_dir),
  ]
}

component("crash_keys") {
  sources = [
    "crash_keys.cc",
    "crash_keys.h",
  ]
  deps = [ "//base" ]
  configs += [ "//build/config/compiler:wexit_time_destructors" ]
  defines = [ "IS_NETWORK_CPP_CRASH_KEYS_IMPL" ]
}

component("cpp") {
  output_name = "network_cpp"

  # Each defines an anonymous-namespace kHeaderName, as do its siblings.
  shot_jumbo_excluded_sources = [
    "declarative_performance_observer_parser.cc",
    "document_isolation_policy_parser.cc",
  ]

  sources = [
    "avail_language_header_parser.cc",
    "constants.cc",
    "content_decoding_interceptor.cc",
    "content_language_parser.cc",
    "cors/cors.cc",
    "cors/origin_access_list.cc",
    "cross_origin_embedder_policy_parser.cc",
    "cross_origin_opener_policy_parser.cc",
    "data_pipe_to_source_stream.cc",
    "declarative_performance_observer_parser.cc",
    "document_isolation_policy_parser.cc",
    "fence_event_reporting_parser.cc",
    "header_util.cc",
    "ip_address_space_util.cc",
    "link_header_parser.cc",
    "loading_params.cc",
    "net_adapters.cc",
    "no_vary_search_header_parser.cc",
    "not_implemented_url_loader_factory.cc",
    "origin_agent_cluster_parser.cc",
    "parsed_headers.cc",
    "request_destination.cc",
    "request_mode.cc",
    "self_deleting_url_loader_factory.cc",
    "shared_url_loader_factory.cc",
    "single_request_url_loader_factory.cc",
    "source_stream_to_data_pipe.cc",
    "sri_message_signatures.cc",
    "supports_loading_mode/supports_loading_mode_parser.cc",
    "timing_allow_origin_parser.cc",
    "unencoded_digests.cc",
    "url_util.cc",
    "wrapper_shared_url_loader_factory.cc",
    "x_frame_options_parser.cc",
  ]

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  public_deps = [
    ":buildflags",
    ":cpp_base",
    ":flags_and_switches",
    ":is_potentially_trustworthy",
    "//net",
    "//services/network/public/mojom",
    "//services/network/public/mojom:url_loader_base",
    "//url",
  ]

  deps = [
    "//base",
    "//components/link_header_util",
    "//net",
  ]

  defines = [ "IS_NETWORK_CPP_IMPL" ]
  if (is_shot_build) {
    defines += [ "IS_SHOT_BUILD" ]
  }
}

# These interfaces are put in their own target so that modules that only
# need to depend on mojom_ip_address does not depend on the entire cpp_base.
component("ip_address_mojom_support") {
  sources = [
    "address_family_mojom_traits.cc",
    "address_family_mojom_traits.h",
    "address_list_mojom_traits.cc",
    "address_list_mojom_traits.h",
    "alternate_protocol_usage_mojom_traits.cc",
    "alternate_protocol_usage_mojom_traits.h",
    "connection_endpoint_metadata_mojom_traits.cc",
    "connection_endpoint_metadata_mojom_traits.h",
    "host_resolver_endpoint_result_mojom_traits.cc",
    "host_resolver_endpoint_result_mojom_traits.h",
    "ip_address_mojom_traits.cc",
    "ip_address_mojom_traits.h",
    "ip_endpoint_mojom_traits.cc",
    "ip_endpoint_mojom_traits.h",
  ]
  deps = [
    "//net",
    "//services/network/public/mojom:mojom_ip_address_shared",
  ]
  configs += [ "//build/config/compiler:wexit_time_destructors" ]
  defines = [ "IS_NETWORK_CPP_IP_ADDRESS_IMPL" ]
}


component("integrity_metadata_mojom_support") {
  sources = [
    "integrity_metadata.cc",
    "integrity_metadata.h",
    "integrity_metadata_mojom_traits.cc",
    "integrity_metadata_mojom_traits.h",
  ]
  deps = [
    "//services/network/public/mojom:mojom_integrity_algorithm",
    "//services/network/public/mojom:mojom_integrity_metadata_shared",
  ]
  defines = [ "IS_NETWORK_CPP_INTEGRITY_METADATA_IMPL" ]
}

component("integrity_policy") {
  sources = [
    "integrity_policy.cc",
    "integrity_policy.h",
    "integrity_policy_mojom_traits.cc",
    "integrity_policy_mojom_traits.h",
    "integrity_policy_parser.cc",
    "integrity_policy_parser.h",
  ]
  deps = [
    ":flags_and_switches",
    "//net",
    "//services/network/public/mojom:mojom_integrity_policy_shared",
  ]
  defines = [ "IS_NETWORK_CPP_INTEGRITY_POLICY_IMPL" ]
}

component("cookies_mojom_support") {
  sources = [
    "cookie_manager_shared_mojom_traits.cc",
    "cookie_manager_shared_mojom_traits.h",
  ]
  deps = [
    ":crash_keys",
    ":first_party_sets_mojom_support",
    ":schemeful_site_mojom_support",
    "//net",
    "//services/network/public/mojom:cookies_mojom_shared",
  ]
  configs += [ "//build/config/compiler:wexit_time_destructors" ]
  defines = [ "IS_NETWORK_CPP_COOKIES_IMPL" ]
}

component("network_param_mojom_support") {
  sources = [
    "auth_mojom_traits.cc",
    "auth_mojom_traits.h",
    "cert_verify_result_mojom_traits.cc",
    "cert_verify_result_mojom_traits.h",
    "ct_policy_status_mojom_traits.cc",
    "ct_policy_status_mojom_traits.h",
    "hash_value_mojom_traits.cc",
    "hash_value_mojom_traits.h",
    "http_response_headers_mojom_traits.cc",
    "http_response_headers_mojom_traits.h",
    "network_param_mojom_traits.cc",
    "network_param_mojom_traits.h",
    "ocsp_verify_result_mojom_traits.cc",
    "ocsp_verify_result_mojom_traits.h",
    "sct_status_flags_mojom_traits.cc",
    "sct_status_flags_mojom_traits.h",
    "signed_certificate_timestamp_and_status_mojom_traits.cc",
    "signed_certificate_timestamp_and_status_mojom_traits.h",
    "signed_certificate_timestamp_mojom_traits.cc",
    "signed_certificate_timestamp_mojom_traits.h",
    "ssl_info_mojom_traits.cc",
    "ssl_info_mojom_traits.h",
    "x509_certificate_mojom_traits.cc",
    "x509_certificate_mojom_traits.h",
  ]
  deps = [
    "//mojo/public/cpp/base:shared_typemap_traits",
    "//net",
    "//services/network/public/mojom:mojom_network_param_shared",
    "//url/mojom:url_mojom_origin",
  ]
  configs += [ "//build/config/compiler:wexit_time_destructors" ]
  defines = [ "IS_NETWORK_CPP_NETWORK_PARAM_IMPL" ]
}

source_set("traffic_annotation_mojom_support") {
  sources = [ "mutable_network_traffic_annotation_tag_mojom_traits.h" ]
  deps = [
    "//net/traffic_annotation",
    "//services/network/public/mojom:mojom_traffic_annotation_shared",
  ]
}

component("structured_headers_mojom_support") {
  sources = [
    "structured_headers_mojom_traits.cc",
    "structured_headers_mojom_traits.h",
  ]
  deps = [
    "//base",
    "//mojo/public/mojom/base",
    "//net",
    "//services/network/public/mojom:mojom_structured_headers_shared",
  ]
  configs += [ "//build/config/compiler:wexit_time_destructors" ]
  defines = [ "IS_NETWORK_CPP_STRUCTURED_HEADERS_IMPL" ]
}

component("flags_and_switches") {
  sources = [
    "features.cc",
    "features.h",
    "network_switches.cc",
    "network_switches.h",
    "web_sandbox_flags.cc",
    "web_sandbox_flags.h",
  ]
  public_deps = [
    "//base",
    "//net",
    "//services/network/public/mojom:mojom_web_sandbox_flags",
    "//url",
  ]
  configs += [ "//build/config/compiler:wexit_time_destructors" ]
  defines = [ "IS_NETWORK_CPP_FLAGS_AND_SWITCHES_IMPL" ]
}

component("is_potentially_trustworthy") {
  sources = [
    "is_potentially_trustworthy.cc",
    "is_potentially_trustworthy.h",
  ]
  public_deps = [
    ":flags_and_switches",
    "//base",
    "//net",
    "//url",
  ]
  configs += [ "//build/config/compiler:wexit_time_destructors" ]
  defines = [ "IS_NETWORK_CPP_IS_POTENTIALLY_TRUSTWORTHY_IMPL" ]
}

component("web_platform") {
  sources = [
    "client_hints.cc",
    "client_hints.h",
    "content_security_policy/content_security_policy.cc",
    "content_security_policy/content_security_policy.h",
    "content_security_policy/csp_context.cc",
    "content_security_policy/csp_context.h",
    "content_security_policy/csp_source.cc",
    "content_security_policy/csp_source.h",
    "content_security_policy/csp_source_list.cc",
    "content_security_policy/csp_source_list.h",
    "cors/origin_access_entry.cc",
    "cors/origin_access_entry.h",
    "permissions_policy/client_hints_permissions_policy_mapping.cc",
    "permissions_policy/client_hints_permissions_policy_mapping.h",
    "permissions_policy/fenced_frame_permissions_policies.h",
    "permissions_policy/origin_with_possible_wildcards.cc",
    "permissions_policy/origin_with_possible_wildcards.h",
    "permissions_policy/permissions_policy.cc",
    "permissions_policy/permissions_policy.h",
    "permissions_policy/permissions_policy_declaration.cc",
    "permissions_policy/permissions_policy_declaration.h",
    "permissions_policy/permissions_policy_features.cc",
    "permissions_policy/permissions_policy_features.h",
    "permissions_policy/permissions_policy_features_bitset.cc",
    "permissions_policy/permissions_policy_features_bitset.h",
    "permissions_policy/permissions_policy_features_generated.h",
    "permissions_policy/permissions_policy_features_internal.cc",
    "permissions_policy/permissions_policy_features_internal.h",
    "permissions_policy/permissions_policy_mojom_traits.cc",
    "permissions_policy/permissions_policy_mojom_traits.h",
  ]
  sources += get_target_outputs(":make_generated_permissions_policy_features")
  public_deps = [
    ":flags_and_switches",
    ":is_potentially_trustworthy",
    ":make_generated_permissions_policy_features",
    "//net",
    "//services/network/public/mojom:mojom_content_security_policy",
    "//services/network/public/mojom:mojom_cors_origin_pattern",
    "//services/network/public/mojom:mojom_origin_or_wildcard_header_value",
    "//services/network/public/mojom:mojom_permissions_policy_shared",
    "//services/network/public/mojom:url_loader_base_shared",
    "//url",
  ]
  configs += [ "//build/config/compiler:wexit_time_destructors" ]
  defines = [ "IS_NETWORK_CPP_WEB_PLATFORM_IMPL" ]
}

# This component is separate from cpp_base as it is a dependency of
# //services/network/public/mojom:url_loader_base.
component("cross_origin_embedder_policy") {
  sources = [
    "cross_origin_embedder_policy.cc",
    "cross_origin_embedder_policy.h",
    "cross_origin_embedder_policy_mojom_traits.cc",
    "cross_origin_embedder_policy_mojom_traits.h",
  ]

  deps = [
    "//base",
    "//mojo/public/mojom/base",
    "//services/network/public/mojom:url_loader_base_shared",
  ]

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  defines = [ "IS_NETWORK_CPP_CROSS_ORIGIN_IMPL" ]
}

# This component is separate from cpp_base as it is a dependency of
# //services/network/public/mojom:url_loader_base.
component("document_isolation_policy") {
  sources = [
    "document_isolation_policy.cc",
    "document_isolation_policy.h",
    "document_isolation_policy_mojom_traits.cc",
    "document_isolation_policy_mojom_traits.h",
  ]

  deps = [
    "//base",
    "//mojo/public/mojom/base",
    "//services/network/public/mojom:url_loader_base_shared",
  ]

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  defines = [ "IS_NETWORK_CPP_DOCUMENT_ISOLATION_IMPL" ]
}

# This component is separate from cpp_base as it is a dependency of
# //services/network/public/mojom:cookies_mojom.
component("schemeful_site_mojom_support") {
  sources = [
    "schemeful_site_mojom_traits.cc",
    "schemeful_site_mojom_traits.h",
  ]
  deps = [
    "//net",
    "//services/network/public/mojom:mojom_schemeful_site_shared",
    "//url/mojom:url_mojom_origin",
  ]
  configs += [ "//build/config/compiler:wexit_time_destructors" ]
  defines = [ "IS_NETWORK_CPP_SCHEMEFUL_IMPL" ]
}

# This component is separate from cpp_base as it is a dependency of
# //services/network/public/mojom:cookies_mojom.
component("first_party_sets_mojom_support") {
  sources = [
    "first_party_sets_mojom_traits.cc",
    "first_party_sets_mojom_traits.h",
  ]
  deps = [
    ":schemeful_site_mojom_support",
    "//mojo/public/cpp/base:shared_typemap_traits",
    "//net",
    "//services/network/public/mojom:mojom_first_party_sets_shared",
  ]
  configs += [ "//build/config/compiler:wexit_time_destructors" ]
  defines = [ "IS_FIRST_PARTY_SETS_MOJOM_TRAITS_IMPL" ]
}

# This component is separate from cpp_base as it is a dependency of
# //services/network/public/mojom:cookies_mojom.
component("storage_access_api_mojom_support") {
  sources = [
    "storage_access_api_mojom_traits.cc",
    "storage_access_api_mojom_traits.h",
  ]
  deps = [
    "//mojo/public/cpp/base:shared_typemap_traits",
    "//net",
    "//services/network/public/mojom:mojom_storage_access_api_shared",
  ]
  defines = [ "IS_STORAGE_ACCESS_API_MOJOM_TRAITS_IMPL" ]
}

component("cpp_base") {
  output_name = "network_cpp_base"

  sources = [
    "cookie_setting_overrides_mojom_traits.cc",
    "cookie_setting_overrides_mojom_traits.h",
    "cors/cors_error_status.cc",
    "cors/cors_error_status.h",
    "cors/cors_mojom_traits.cc",
    "cors/cors_mojom_traits.h",
    "cross_origin_opener_policy.cc",
    "cross_origin_opener_policy.h",
    "cross_origin_opener_policy_mojom_traits.cc",
    "cross_origin_opener_policy_mojom_traits.h",
    "data_element.cc",
    "data_element.h",
    "http_request_headers_mojom_traits.cc",
    "http_request_headers_mojom_traits.h",
    "http_request_headers_update_params.cc",
    "http_request_headers_update_params.h",
    "isolation_info_mojom_traits.cc",
    "isolation_info_mojom_traits.h",
    "load_timing_info_mojom_traits.cc",
    "load_timing_info_mojom_traits.h",
    "load_timing_internal_info_mojom_traits.cc",
    "load_timing_internal_info_mojom_traits.h",
    "network_anonymization_key_mojom_traits.cc",
    "network_anonymization_key_mojom_traits.h",
    "network_isolation_key_mojom_traits.cc",
    "network_isolation_key_mojom_traits.h",
    "network_types_mojom_traits.h",
    "originating_process_id.cc",
    "originating_process_id.h",
    "renderer_process_id.h",
    "resource_request.cc",
    "resource_request.h",
    "resource_request_body.cc",
    "resource_request_body.h",
    "source_type_mojom_traits.cc",
    "source_type_mojom_traits.h",
    "transferable_directory.cc",
    "transferable_directory.h",
    "transferable_socket.cc",
    "transferable_socket.h",
    "trust_token_parameterization.h",
    "url_loader_completion_status.cc",
    "url_loader_completion_status.h",
    "url_loader_completion_status_mojom_traits.cc",
    "url_loader_completion_status_mojom_traits.h",
    "url_request_mojom_traits.cc",
    "url_request_mojom_traits.h",
    "url_request_param_mojom_traits.cc",
    "url_request_param_mojom_traits.h",
    "url_request_redirect_info_mojom_traits.h",
  ]

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  public_deps = [
    ":cookies_mojom_support",
    ":crash_keys",
    ":cross_origin_embedder_policy",
    ":document_isolation_policy",
    ":integrity_metadata_mojom_support",
    ":integrity_policy",
    ":ip_address_mojom_support",
    ":network_param_mojom_support",
    ":traffic_annotation_mojom_support",
    ":schemeful_site_mojom_support",
    ":storage_access_api_mojom_support",
    ":structured_headers_mojom_support",
    ":web_platform",
    "//services/network/public/mojom:url_loader_base",
    "//url/mojom:url_mojom_gurl",
    "//url/mojom:url_mojom_origin",
  ]
  deps = [
    ":buildflags",
    ":first_party_sets_mojom_support",
    "//base",
    "//mojo/public/mojom/base",
    "//net",
    "//services/network/public/mojom:cookies_mojom",
    "//services/network/public/mojom:mojom_first_party_sets",
    "//services/network/public/mojom:mojom_network_isolation_key",
    "//services/network/public/mojom:mojom_storage_access_api",
    "//services/network/public/mojom:url_loader_base",
  ]
  defines = [ "IS_NETWORK_CPP_BASE_IMPL" ]

  if (is_fuchsia) {
    sources += [ "transferable_directory_fuchsia.cc" ]
  }

  # TODO(crbug.com/40915226): Remove the need to ignore this warning.
  if (is_win && is_component_build) {
    ldflags = [ "/IGNORE:4217" ]
  }
}
