# Copyright 2017 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//mojo/public/tools/bindings/mojom.gni")

mojom("mojom") {
  generate_java = true

  sources = [
    "screen_info.mojom",
    "screen_infos.mojom",
    "screen_orientation.mojom",
  ]

  public_deps = [
    "//ui/gfx/geometry/mojom",
    "//ui/gfx/mojom",
  ]

  shared_cpp_typemaps = [
    {
      types = [
        {
          mojom = "display.mojom.ScreenInfo"
          cpp = "::display::ScreenInfo"
        },
      ]
      traits_headers = [ "screen_info_mojom_traits.h" ]
      traits_public_deps = [ ":shared_mojom_traits" ]
    },
    {
      types = [
        {
          mojom = "display.mojom.ScreenInfos"
          cpp = "::display::ScreenInfos"
        },
      ]
      traits_headers = [ "screen_infos_mojom_traits.h" ]
      traits_public_deps = [ ":shared_mojom_traits" ]
    },
  ]

  cpp_typemaps = shared_cpp_typemaps
  blink_cpp_typemaps = shared_cpp_typemaps
}

component("shared_mojom_traits") {
  output_name = "display_shared_mojom_traits"
  defines = [ "IS_DISPLAY_SHARED_MOJOM_TRAITS_IMPL" ]
  configs += [ "//build/config/compiler:wexit_time_destructors" ]
  sources = [
    "screen_info_mojom_traits.cc",
    "screen_info_mojom_traits.h",
    "screen_infos_mojom_traits.cc",
    "screen_infos_mojom_traits.h",
  ]
  public_deps = [
    ":mojom_shared",
    "//base",
    "//ui/display",
    "//ui/gfx/mojom",
  ]
}
